name:         galexy-blog
version:      0.1.0
author:       "Galex Yen"
license:      BSD3
copyright:    "2019 Galex Yen"

extra-source-files:
- README.md

library:
  source-dirs: src

dependencies:
- base

executables:
  site:
    main:         Main.hs
    source-dirs:  app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hakyll
    - galexy-blog